In [1]:
import numpy as np

In [2]:
ar=np.array([1,2,3,4])

In [3]:
ar.dtype

dtype('int32')

In [4]:
print ("dimension=",ar.ndim,"taille=",ar.size,"forme=",ar.shape)

dimension= 1 taille= 4 forme= (4,)


In [5]:
ar[1]

2

In [6]:
print("ar[-1]=" , ar[-1]," et ar[-2]=", ar[-2])

ar[-1]= 4  et ar[-2]= 3


In [7]:
ar1 = np.array([[1, 2, 3],[4, 5, 6]])

In [8]:
ar1[1,0]

4

In [9]:
ar1[0,0]=7

In [10]:
ar1

array([[7, 2, 3],
       [4, 5, 6]])

In [11]:
ar1[1,2]=np.pi

In [12]:
ar1

array([[7, 2, 3],
       [4, 5, 3]])

In [13]:
ar2 = np.arange(0,20,3)

In [14]:
ar2

array([ 0,  3,  6,  9, 12, 15, 18])

In [15]:
ar3 = ar2[:5]

In [16]:
ar3

array([ 0,  3,  6,  9, 12])

In [17]:
ar3[:4:2]

array([0, 6])

In [18]:
ar3[3::-1]

array([9, 6, 3, 0])

In [19]:
ar1.shape

(2, 3)

In [20]:
ar4 = ar1.reshape(3, 2)

In [21]:
ar4

array([[7, 2],
       [3, 4],
       [5, 3]])